### ISSUE TITLE
Zero direct messages

### ISSUE THREAD

**Issue by Gamathh** [alkihis/twitter-archive-reader#4]
Hello, the reader finds all tweets perfectly but cannot read the direct messages from my file, as if there isn't none. The zip have .js files related to DMs, but the reader count 0 DMs.

Thank you very much.
![tt1](https://user-images.githubusercontent.com/60792424/74054063-fc5eba80-49bb-11ea-89b1-292394475850.PNG)
![tt2](https://user-images.githubusercontent.com/60792424/74054066-fd8fe780-49bb-11ea-903a-29362fa4c9a7.PNG)

**Comment by alkihis** [comment]
Can you paste the beginning of the `direct-message.js` file here ? (you can delete `text` properties to anonymize it if you want)

**Comment by Gamathh** [comment]
From the _direct-messages.js_ file:

window.YTD.direct_messages.part0 = [ {
  "dmConversation" : {
    "conversationId" : "34914032-2509346272",
    "messages" : [ {
      "messageCreate" : {
        "recipientId" : "2509346272",
        "text" : "**.**",
        "mediaUrls" : [ ],
        "senderId" : "34914032",
        "id" : "826958430795603972",
        "createdAt" : "2017-02-02T01:00:28.774Z"
      }
    } ]
  }
}, {
  "dmConversation" : {
    "conversationId" : "41289543-2509346272",
    "messages" : [ {
      "messageCreate" : {
        "recipientId" : "2509346272",
        "text" : "**.**",
        "mediaUrls" : [ ],
        "senderId" : "41289543",
        "id" : "892164719188094979",
        "createdAt" : "2017-07-31T23:26:59.397Z"
      }
    }

**Comment by alkihis** [comment]
The file seems ok. Maybe Twitter has renamed `direct-message.js` and `direct-message-group.js` into `direct-messages.js` or something else ? If it's that, i'll fix it soon.

**Comment by Gamathh** [comment]
I renamed the files and loaded, now everything is fine. Thank you!

**Comment by alkihis** [comment]
Addressed in [a53c94](https://github.com/alkihis/twitter-archive-reader/commit/a53c94235210cba5f4781beb337dada6f8890750).
Should be deployed to Archive Explorer in a few days !
